config/routes.rb
Ecc::Application.routes.draw do
  

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  resources :home_teams
  resources :teams
  resources :matches
  resources :venues
  resources :news do 
    get 'store'

    
  end
  
  match "/news/val_new_news" => "news#val_new_news"
  match "/news/val_edit_news" => "news#val_edit_news"
  
  
  
  resources :players
                     
  get "home/index"

  match "/intelligence" => "matches#index"
  match "/players/:id" => "players#show"

  
  root :to => "home#index" 
  devise_for :users
  

end

app/models/match.rb
class Match < ActiveRecord::Base
  belongs_to :venue
  belongs_to :opposition
  belongs_to :our_team
  
  
  scope :fixtures, where("matches.match_date > '#{Time.now}'").order("matches.match_date")
  scope :short_fixtures, limit(9).fixtures
  scope :our_results, where("matches.match_date < '#{Time.now}'")
  scope :latest_results, limit(10).our_results.order("matches.match_date DESC")
  
  
  #check if match has no results (then it's a fixture)
  def fixture?
    self.result == nil
  end
  
  
  def self.summary_results
    won = Match.where(:result => "Won").count
    drawn = Match.where(:result => "Draw").count
    lost = Match.where(:result => "Lost").count
    return [won, drawn, lost]
  end

  def guess_result
    # puts home_runs
    # puts away_runs
    case our_runs <=> opposition_runs
    when 1
      return "W"
    when -1
      return "L"
    when 0
      return "D"
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  # GET /matches
  # GET /matches.json
  def index
    @matches = Match.our_results(:order => 'match_date DESC', :limit  => 30)
    
    
    #todo- much nicer way to do this I'm sure
    month_names = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    #construct the structure of the fixtures for display
    
    fixtures = Match.all(:order => "match_date")
    @fix_table = {}
    
    fixtures.each do |fix|
    
      month = month_names[fix.match_date.month]
    
      @fix_table[month] = [] unless @fix_table.has_key?(month)
      
      if fix.venue.name.nil?
        venue = "Unknown"
      else
        
      if fix.venue.name == "Elsworth"
        venue = "Home"
      else
        venue = "Away"
      end
    end
    
      
      delim = "/"
      
      delim = "" if fix.our_runs.nil?
      
      #find out the month
      @fix_table[month] << {
        "team" => fix.our_team.name,
        "opposition" => fix.opposition.name,
        "our_score" => "#{fix.our_runs} #{delim} #{fix.our_wickets}",
        "opp_score" => "#{fix.opposition_runs} #{delim} #{fix.opposition_wickets}",
        "match_date" => fix.match_date,
        "result" => fix.result,
        "venue" => venue
      }
      
  end
    
    
    
    
    @results = Match.summary_results
    
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @matches }
    end
  end

  # GET /matches/1
  # GET /matches/1.json
  def show
    @match = Match.find(params[:id])
    
    #choose view based on fixture or result
    if @match.fixture?
      render 'fixture' 
    else  
      
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @match }
    end
  end
  
  end
  
  def new
    @match = Match.new
    @match.match_date = Match.last.match_date + 7
    @match.our_team_id = 1
    @match.opposition_id = 2
  end
  
  def create
    @match = Match.new(params[:match])
    @match.result =  @match.guess_result if @match.result.blank?
    
    respond_to do |format|
      if @match.save
        format.html { redirect_to(matches_path, :notice => 'Match was successfully created.') }
        format.xml  { render :xml => @match, :status => :created, :location => @match }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @match.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def edit
    @match = Match.find(params[:id])
  end     
  
  def update
    @match = Match.find(params[:id])

    respond_to do |format|
      if @match.update_attributes(params[:match])
        format.html { redirect_to matches_path, notice: 'Match was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @match.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @match = Match.find(params[:id])
    @match.destroy

    respond_to do |format|
      format.html { redirect_to matches_url }
      format.json { head :ok }
    end
  end


  
end

app/helpers/matches_helper.rb
module MatchesHelper

  def label_result(result)
    result = result[0].upcase
    case result
    when "W"
      return "success"
    when "L"
      return "important"
    when "D"
      return "warning"
    else 
      return "default"
    end
  end

  # Checks result against word, e.g. "Won" against "Won" and returns formatted span
  def span_result(result, word)
    if result == word
      result_short = result[0].upcase
      label_style = case result_short
        when "W"
          "success"
        when "L"
          "important"
        when "D"
          "warning"
        else 
          "default"
        end
        return "<span class='label #{label_style}'>#{word}</span>".html_safe
      else                                                         
        return "<span class='label default'>#{word}</span>".html_safe
      end
  end
  
 
  def draw_progress_bar(max, our, opp, result)
    our_perc = (our.to_f/max.to_f)*100
    opp_perc = (opp.to_f/max.to_f)*100
    # debugger
    colour = case result[0].upcase
      when "W"
        '#46a546'
      when "L" 
        '#C43C35'
      when "D" 
        '#F89406'
      else
        '#BFBFBF'
      end
    our_out = "<div style='position:absolute; top:0; left: 0; width: #{our_perc}%; height:20px; background-color: #{colour}; text-align:center'>Our</div>"
    opp_out = "<div style='position:absolute; top:0; left: 0; z-index: 10; width: #{opp_perc}%; height:20px; background-color: #{colour}; text-align:center'>Opp</div>"
    output = our_out + opp_out
    return output.html_safe
    
  end

end

app/views/matches/_result.html.erb
  <div class="row well">
  <!-- <div class="row"> -->
    <!-- <div class="row slim" id="main_results"> -->
    <div class="slim" id="main_results">
      <!-- <div id="main_detail" class="span8"> -->
        <%= link_to "Edit", edit_match_path(result) %>
        <h2>
          <small>vs</small>
          <%= Opposition.find(result.opposition_id).name %>
          </h2>
      <!-- </div> -->
      <!-- <div id="sidebar" class="span4"> -->
      <div id="sidebar">
        <!-- <div class="row"> -->
          <div class="span4" style="text-align:right; float:right">
          <%= span_result(result.result, 'Won') %>
          <%= span_result(result.result, 'Drawn') %>
          <%= span_result(result.result, 'Lost') %>
          </div>
          <div class="span4" style="text-align:right; float:right">
            <small><%= result.match_date.strftime("#{result.match_date.day.ordinalize} %b '%y") %></small>
          </div>
        <!-- </div>  -->
      </div>
    </div>
  
    <!-- <div id="score_detail" class="row slim"> -->
    <div id="score_detail" class="slim">
      <div class="span4 offset2">
        <h1 style="margin-bottom:0px"><%= result.our_runs || '-' %>
          <small>for</small>
          <%= result.our_wickets %>
        </h1>
      </div>    
      <div class="span4">
        <h1 style="margin-bottom:0px"><%= result.opposition_runs || '-' %>
          <small>for</small>
          <%= result.opposition_wickets %>
        </h1>
      </div>    
    </div>
    
    <!-- <div id="score_graphic" class="row slim"> -->
    <div id="score_graphic" class="slim">
      <div style="position: relative, height: 20px; width: 100%">
        <%= draw_progress_bar(@progress_bar, result.our_runs, result.opposition_runs, result.result) %>
      </div> 
    </div>
  </div> 

app/views/matches/_result_small.html.haml
.row.result_box
  = form_for :result do |f|
    .edit_link
      = f.submit "Submit", :disable_with => 'Submiting...'
      = link_to "Edit", edit_match_path(result) unless result.all_present? 
    .span7
      .row
        %h2
          %small vs
          = Opposition.find(result.opposition_id).name
        .span3
          %h1{:style => "margin-bottom:0px"}
            = f.text_field :our_runs
            %small for
            = result.our_wickets || '-'
        .span4
          %h1{:style => "margin-bottom:0px"}
            = result.opposition_runs || '-'
            %small for
            = result.opposition_wickets || '-'
    .span3{:style => 'text-align = right; float:right'} 
      = span_result(result.result, 'Won')
      = span_result(result.result, 'Drawn')
      = span_result(result.result, 'Lost')

app/views/matches/fixture.html.erb
	


<div class="container">
	
	<h1  style="margin-top:80px;"><%= @match.match_date.to_formatted_s(:long) %> </h1>
	<h1 id="">Elsworth <%=@match.our_team.name%> vs <%= @match.opposition.name%></h1>	 
  


<div class="row">
    
  
    <div class="span12 columns">
      <h2 class="page-header">Where is the Venue?</h2>
	  		  
			<div class="thumbnail">
				<div id="map" style="height: 400px"></div>
				<div class="caption">
          <h5>The venue is 5km from a decent pint and cheesy chips </h5>
        </div>
			</div>


				<%= javascript_include_tag "leaflet.js" %>
				<%= stylesheet_link_tag    "leaflet.css" %>
				
				
				<script>
							var cloudmadeUrl = 'http://{s}.tile.cloudmade.com/BC9A493B41014CAABB98F0471D759707/997/256/{z}/{x}/{y}.png',
								cloudmade = new L.TileLayer(cloudmadeUrl, {maxZoom: 20});

							var map = new L.Map('map');
							map.setView(new L.LatLng(<%= @match.venue.venue_lat %>, <%= @match.venue.venue_lng %>), 16).addLayer(cloudmade);
							var LeafIcon = L.Icon.extend({
							    iconUrl: "<%= asset_path 'marker.png' %>",
									    shadowUrl: "<%= asset_path 'marker-shadow.png' %>"
							    
							});
						
							var greenIcon = new LeafIcon(),
							    marker = new L.Marker(new L.LatLng(<%= @match.venue.venue_lat %>, <%= @match.venue.venue_lng %>), {icon: greenIcon});
						
						map.addLayer(marker);
					
				</script>
	
	
	
	 
      <br/>

      
	    
    </div>
  </div>  
</div>

app/views/matches/index.html.erb
<div class="container well" style="padding-top:60px">
<h1>2012 Fixtures and Results</h1>


<% @fix_table.each_key do |mon|%>
	<h2 style="margin-top: 16px; margin-bottom: 13px;"><%= mon %></h2>
	<table class="table table-striped">
		<thead>
      <tr>
				<th>Date</th>
        <th>Team</th>
				<th>&nbsp</th>
				<th>&nbsp</th>
				<th>&nbsp</th>
        <th>Opposition</th>
        
        <th>Location</th>
				<th>Result</th>
      </tr>
    </thead>

		<tbody>
		
	<% @fix_table[mon].each do |game| %>
	
			<tr>
				<th><%= game["match_date"].to_s(:long) %></th>
        <th>Elsworth <%= game["team"]%></th>
				<th><%= game["our_score"]%></th>
				<th>vs</th>
				<th><%= game["opp_score"] %></th>
        <th><%= game["opposition"] %></th>
        
        <th><%= game["venue"]%> </th>
				<th><span class="label" style="background-color: #075220;"><%= game["result"]%> </span></th>
      </tr>
	
	<% end %>
		
			
		</tbody>
	</table>




<% end %>

app/views/matches/season.html.erb
<div class="container">
  <div class="row">
    <div class="span16">
      <h1>Season results for <%= @year %> <small>fixed for 1st XI at the moment</small></h1>
      <!-- TODO: Allow choice between Our_teams -->
    </div>
  </div>
  <div class="row">
    <div class="span12">
      <% @results.each do |result|%>
        <%= render :partial => 'result_small', :locals => {:result => result} %>
      <% end %>         
    </div> 
    <div class="span4">
      <h2>Season summary</h2>
      <table>
          <tr>
            <td>Won</td> 
            <td><span class="label success" style="font-size: 20px"><%= @summary[0] %></span></td>
          </tr>
          <tr>
            <td>Drawn</td>
            <td><span class="label warning" style="font-size: 20px"><%= @summary[1] %></span></td>
          </tr>
          <tr>
            <td>Lost</td>
            <td><span class="label important" style="font-size: 20px"><%= @summary[2] %></span></td>
          </tr>
      </table>
    </div>
  </div>
</div>